node-ui-property-element = Élément d'interface de propriété
node-ui-submit-create = Créer
node-ui-submit-update = Mettre à jour
facet-mode-apply = Appliquer les filtres
facet-type-selector-label = Type
loading = Chargement
property-add-value =
    .aria-label = Ajouter une valeur
property-remove-value =
    .aria-label = Supprimer la valeur
details-editor-options =
    .aria-label = Options du champ
select-an-option = - Sélectionner une option -
create-new-reference-option = Créer…
create-new-reference-title = Nouvel élément
create-new-reference-done = Terminé
widget-switcher-label = Choisir un widget
widget-switcher-tooltip = Choisissez l'éditeur utilisé pour ce champ. Différents widgets peuvent proposer différentes façons de saisir la même valeur.
logical-constraint-switcher-label = Choisir une alternative
logical-constraint-switcher-tooltip = Ce champ accepte plusieurs types de valeurs. Choisissez celle que vous souhaitez saisir, puis remplissez les champs qui apparaissent ci-dessous.
drawer-property-group-add-label = Ajouter une propriété
content-language-switcher-label = Langue du contenu
content-language-switcher-tooltip = La langue du contenu détermine quelle traduction d'une valeur (par exemple un nom ou une description) est affichée et modifiée. Elle ne change pas les libellés et boutons qui l'entourent.
interface-language-switcher-label = Langue de l'interface
interface-language-switcher-tooltip = La langue de l'interface détermine la langue des libellés, boutons et autres textes à l'écran. Elle ne change pas les valeurs traduites que vous modifiez.
content-language-create-option = Ajouter une langue…
content-language-create-title = Ajouter une langue de contenu
content-language-create-label = Code de langue
content-language-create-hint = Saisissez un code de langue BCP 47, par exemple en-GB ou fr-FR.
content-language-create-preview = Aperçu : { $label }
content-language-create-error-invalid = Ce n'est pas un code de langue BCP 47 valide.
content-language-create-error-duplicate = Cette langue figure déjà dans la liste.
content-language-create-cancel = Annuler
content-language-create-submit = Ajouter
content-language-delete-option =
    .aria-label = Supprimer le contenu en { $language }
content-language-delete-title = Supprimer le contenu de la langue
content-language-delete-message = Supprimer toutes les valeurs en { $language } ? Cette action les supprime entièrement des données et ne peut pas être annulée.
content-language-delete-cancel = Annuler
content-language-delete-confirm = Supprimer
modal-close =
    .aria-label = Fermer
form-element-help =
    .aria-label = Aide
form-element-required =
    .aria-label = Obligatoire
form-element-required-tooltip = Ce champ est obligatoire
autocomplete-search-placeholder =
    .placeholder = Rechercher…
autocomplete-no-results = Aucun résultat trouvé
autocomplete-search-error = Échec de la recherche
autocomplete-facet-search-title = Sélectionner une valeur pour { $label }
address-search-placeholder =
    .placeholder = Rechercher une adresse…
autocomplete-edit-value =
    .aria-label = Modifier
autocomplete-option-edit-resource =
    .aria-label = Modifier { $label }
autocomplete-option-discard-title = Abandonner les modifications ?
autocomplete-option-discard-message = Abandonner vos modifications de { $label } ? Cette action est irréversible.
autocomplete-option-discard-cancel = Continuer la modification
autocomplete-option-discard-confirm = Abandonner
blank-node-editor-assign-identifier = Remplacer le nœud imbriqué par un nœud avec identifiant
blank-node-editor-identifier-placeholder =
    .placeholder = Identifiant (IRI)…
member-shape-list-add-item =
    .aria-label = Ajouter un élément
member-shape-list-remove-item =
    .aria-label = Supprimer l'élément
member-shape-list-reorder-item =
    .aria-label = Réorganiser l'élément
property-federated-search-label =
    .aria-label = Recherche fédérée
property-federated-search-tooltip = Ce champ interroge une source de données externe
validation-severity-violation = Erreur :
validation-severity-warning = Avertissement :
validation-severity-info = Info :
fileupload-description = Glissez des fichiers ici ou cliquez pour en sélectionner
fileupload-missing-upload-url = st:uploadUrl est manquant sur la forme de propriété
fileupload-error = Échec du téléversement
duration-editor-days = Jours
duration-editor-hours = Heures
duration-editor-minutes = Minutes
duration-editor-seconds = Secondes
duration-editor-milliseconds = Millisecondes
duration-viewer-years = Années
duration-viewer-months = Mois
duration-viewer-days = Jours
duration-viewer-hours = Heures
duration-viewer-minutes = Minutes
duration-viewer-seconds = Secondes
duration-viewer-milliseconds = Millisecondes
