// Generated by ShapeThing
import { z } from "astro:content";

export const classSchema = z.object({
    iri: z.string(),
    type: z.literal("http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"),
    shape: z.string(),
    label: z.string(),
    description: z.string()
});
