// Generated by @shapething/shacl-renderer
import { z } from "astro:content";

export const OntologyPropertySchema = z.object({
    type: z.string(),
    shapesGraph: z.string(),
    label: z.string(),
    comment: z.string()
});
