// Generated by ShapeThing
import { z } from "astro:content";

export const propertySchema = z.object({
    iri: z.string(),
    type: z.string(),
    shape: z.string(),
    label: z.string(),
    description: z.string()
});
