import LoadingTwotoneLoopIcon from "~icons/line-md/loading-twotone-loop";
import PlusIcon from "~icons/ic/round-add";
import MinusIcon from "~icons/ic/round-remove";
import ArrowDropDown from "~icons/ic/round-arrow-drop-down";
import SwitchLeft from "~icons/ic/round-settings";
import EditIcon from "~icons/ic/round-edit";
import LinkIcon from "~icons/ic/round-link";
import CloseIcon from "~icons/ic/round-close";
import HelpIcon from "~icons/ic/round-help";
import DeleteIcon from "~icons/ic/round-delete-outline";

export const Loading = LoadingTwotoneLoopIcon;
export const Plus = PlusIcon;
export const Minus = MinusIcon;
export const SelectArrow = ArrowDropDown;
export const Cog = SwitchLeft;
export const Edit = EditIcon;
export const Link = LinkIcon;
export const Close = CloseIcon;
export const Help = HelpIcon;
export const Delete = DeleteIcon;
