import type { Literal, NamedNode, Term } from "@rdfjs/types";
import type { RdfStore } from "rdf-stores";
import { Localized } from "@fluent/react";
import ValidationMessages from "@/outputs/render/components/ValidationMessages/index.tsx";
import type { ValidationResult } from "@/outputs/render/contexts/validationContext.tsx";
import { useEnvironment } from "@/outputs/render/hooks/useEnvironment.tsx";
import { useInterfaceLanguage } from "@/outputs/render/hooks/useInterfaceLanguage.tsx";
import { bestByLanguage } from "@/helpers/bestByLanguage.ts";
import { localName } from "@/helpers/localName.ts";
import { localNameLabel } from "@/helpers/localNameLabel.ts";
import { rdf, rdfs, sh } from "@/helpers/namespaces.ts";
import { prefixedIri } from "@/helpers/prefixedIri.tsx";
import { getRdfList } from "@/helpers/rdfList.ts";
import language, { configuredLanguages } from "@/resolution/language.ts";
import { parsePathNode } from "@/structure/paths/parsePropertyPath.ts";
import type { LanguageRange } from "@/types/BCP47.ts";

const SHACL_NAMESPACE = sh("").value;
const KNOWN_SEVERITIES = new Set(["Violation", "Warning", "Info"]);

// Core constraint components whose message is fully described by their own name - there's no
// parameter value worth repeating ("Has more than one value in the same language").
const PARAMETERLESS = new Set(["UniqueLang", "And", "Or", "Xone", "Closed", "SPARQL"]);

const NUMERIC_DATATYPE = /#(integer|decimal|double|float|long|int|short|byte|nonNegativeInteger|positiveInteger|nonPositiveInteger|negativeInteger|unsigned\w+)$/;

type Context = {
  shapesGraph: RdfStore;
  dataGraph: RdfStore;
  sourcePrefixes: Record<string, string>;
  languages: LanguageRange[];
  interfaceLanguage: string;
};

function termLabel(term: Term, context: Context): string | undefined {
  for (const graph of [context.shapesGraph, context.dataGraph]) {
    const label = bestByLanguage(
      [rdfs("label"), sh("name")].flatMap((predicate) =>
        graph.getQuads(term, predicate).map((quad) => quad.object)
      ),
      context.languages,
    );
    if (label) return label.value;
  }
  return undefined;
}

function formatTerm(term: Term, context: Context): string | number | undefined {
  if (term.termType === "Literal") {
    return NUMERIC_DATATYPE.test(term.datatype.value) && !Number.isNaN(Number(term.value))
      ? Number(term.value)
      : term.value;
  }
  if (context.shapesGraph.getQuads(term, rdf("first")).length > 0) {
    const members = getRdfList(term, context.shapesGraph)
      .map((member) => formatTerm(member, context))
      .filter((member) => member !== undefined)
      .map(String);
    return new Intl.ListFormat(context.interfaceLanguage, { type: "disjunction" }).format(members);
  }
  const label = termLabel(term, context);
  if (label) return label;
  // A blank-node parameter (e.g. an inline sh:node [ ... ]) has nothing readable to show.
  if (term.termType !== "NamedNode") return undefined;
  return prefixedIri(term as NamedNode, context.sourcePrefixes) ?? localNameLabel(term) ?? term.value;
}

type Description = { id: string; vars: Record<string, string | number>; precise: boolean };

/**
 * A generated message for a SHACL Core constraint component: precise ("Must have at least 2
 * values") when `constraintShape` holds the constraint's parameter, generic ("Has too few values")
 * when only the component is known - e.g. a report rendered without its shapes.
 */
function describeConstraint(result: ValidationResult, context: Context): Description | undefined {
  const component = result.constraintComponent;
  if (!component || !component.value.startsWith(SHACL_NAMESPACE)) return undefined;
  const name = component.value.slice(SHACL_NAMESPACE.length).replace(/ConstraintComponent$/, "");
  const id = `report-constraint-${name.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase()}`;

  if (PARAMETERLESS.has(name)) return { id, vars: {}, precise: Boolean(result.constraintShape) };

  const parameter = name.charAt(0).toLowerCase() + name.slice(1);
  const parameterValue = result.constraintShape
    ? context.shapesGraph.getQuads(result.constraintShape, sh(parameter))[0]?.object
    : undefined;
  const value = parameterValue ? formatTerm(parameterValue, context) : undefined;
  return value === undefined
    ? { id, vars: { known: "no" }, precise: false }
    : { id, vars: { known: "yes", value }, precise: true };
}

function ResultMessage({ result, context }: { result: ValidationResult; context: Context }) {
  const resultMessage = result.message.length
    ? language(result.message as Literal[], context.languages).value
    : undefined;
  // An sh:message the shape author wrote always wins. Otherwise a report's sh:resultMessage was
  // generated by whichever engine produced it (often as technical as "Less than 1 values on
  // ex:bob->ex:name") - so when the shape is known, a message built from its own parameters is
  // preferred, and the report's own only used when there's nothing better to say.
  const authored =
    result.constraintShape &&
    context.shapesGraph.getQuads(result.constraintShape, sh("message")).length > 0;
  const description = authored ? undefined : describeConstraint(result, context);

  if (resultMessage && (authored || !description?.precise)) return <>{resultMessage}</>;
  if (description) {
    return (
      <Localized id={description.id} vars={description.vars}>
        <span />
      </Localized>
    );
  }
  const constraint = result.constraintComponent;
  return constraint ? (
    <Localized
      id="report-constraint-other"
      vars={{ constraint: formatTerm(constraint, context) ?? constraint.value }}
    >
      <span />
    </Localized>
  ) : null;
}

// A detail's own property, so a nested message reads "Postal code: Does not match ...".
function propertyName(result: ValidationResult, context: Context): string | undefined {
  if (!result.sourceShape) return undefined;
  const name = bestByLanguage(
    context.shapesGraph.getQuads(result.sourceShape, sh("name")).map((quad) => quad.object),
    context.languages,
  );
  if (name) return name.value;
  const pathNode = context.shapesGraph.getQuads(result.sourceShape, sh("path"))[0]?.object;
  try {
    const path = pathNode && parsePathNode(pathNode, context.shapesGraph);
    if (path && path.type === "predicate") {
      return termLabel(path.predicate, context) ?? localNameLabel(path.predicate) ?? undefined;
    }
  } catch {
    // Unparseable path - just no label.
  }
  return undefined;
}

/**
 * sh:detail's nested results, as plain lines inside their parent's own message - "Postal code:
 * Use a Dutch postal code" - rather than as boxed messages of their own nested in the parent's box.
 * A detail can have details of its own, listed (indented) below it.
 */
function DetailList({ results, context }: { results: ValidationResult[]; context: Context }) {
  return (
    <ul className="st-validation-details">
      {results.map((result, index) => {
        const name = propertyName(result, context);
        return (
          <li key={index} className="st-validation-detail">
            {name && <span className="st-validation-message-property">{name}:</span>}
            <ResultMessage result={result} context={context} />
            {result.details?.length ? <DetailList results={result.details} context={context} /> : null}
          </li>
        );
      })}
    </ul>
  );
}

/**
 * Validation results as ValidationMessages: each one's message resolved in the interface language
 * (see ResultMessage), a custom sh:Severity labeled by its own rdfs:label, and sh:detail's nested
 * results listed below their parent's message (see DetailList).
 */
export default function ResultMessages({
  results,
  className,
}: {
  results: ValidationResult[];
  className?: string;
}) {
  const { shapesGraph, dataGraph, sourcePrefixes } = useEnvironment();
  const { activeInterfaceLanguage } = useInterfaceLanguage();
  if (results.length === 0) return null;

  const context: Context = {
    shapesGraph,
    dataGraph,
    sourcePrefixes,
    languages: configuredLanguages(shapesGraph, [activeInterfaceLanguage]),
    interfaceLanguage: activeInterfaceLanguage,
  };

  return (
    <ValidationMessages
      className={className}
      messages={results.map((result) => {
        const severity = localName(result.severity) ?? "Violation";
        return {
          severity,
          severityLabel: KNOWN_SEVERITIES.has(severity)
            ? undefined
            : String(formatTerm(result.severity, context) ?? severity),
          message: <ResultMessage result={result} context={context} />,
          extra: result.details?.length ? (
            <DetailList results={result.details} context={context} />
          ) : undefined,
        };
      })}
    />
  );
}
