const getItems = async (type: 'groups' | 'facets' | 'lists' | 'viewers' | 'editors') => {
  const widgets: string[] = []

  const widgetFiles = Deno.readDir(`./lib/widgets/${type}/`)
  for await (const widget of widgetFiles) {
    widgets.push(`{ meta: ${widget.name}, Component: lazy(() => import('./${type}/${widget.name}/index')) }`)
  }
  return widgets.join(',\n')
}

const getImports = async (type: 'groups' | 'facets' | 'lists' | 'viewers' | 'editors') => {
  const imports: string[] = []
  const widgetFiles = Deno.readDir(`./lib/widgets/${type}/`)
  for await (const widget of widgetFiles) {
    imports.push(`import ${widget.name} from './${type}/${widget.name}/meta'`)
  }
  return imports.join('\n')
}

const template = `
// This file is generated by scripts/generate-coreWidgets.ts
// Do not edit it manually, but run 'npm run generate-widgets' to update
import { ReactNode, lazy } from 'react'
import { WidgetItem } from './widgets-context'
${await getImports('editors')}
${await getImports('viewers')}
${await getImports('facets')}
${await getImports('lists')}
${await getImports('groups')}

export const coreWidgets: {
  editors: WidgetItem[]
  viewers: WidgetItem[]
  facets: WidgetItem[]
  lists: WidgetItem<{ items: ReactNode[] }>[]
  groups: WidgetItem[]
} = {
  editors: [${await getItems('editors')}],
  viewers: [${await getItems('viewers')}],
  facets: [${await getItems('facets')}],
  lists: [${await getItems('lists')}],
  groups: [${await getItems('groups')}],
}`

await Deno.writeTextFile('./lib/widgets/coreWidgets.ts', template)
