
// This file is generated by scripts/generate-coreWidgets.ts
// Do not edit it manually, but run 'npm run generate-widgets' to update
import { ReactNode, lazy } from 'react'
import { WidgetItem } from './widgets-context'
import TextFieldWithLangEditor from './editors/TextFieldWithLangEditor/meta'
import EditorJsEditor from './editors/EditorJsEditor/meta'
import TextFieldEditor from './editors/TextFieldEditor/meta'
import IconifyEditor from './editors/IconifyEditor/meta'
import AutoCompleteEditor from './editors/AutoCompleteEditor/meta'
import ColorEditor from './editors/ColorEditor/meta'
import URIEditor from './editors/URIEditor/meta'
import ClassHierarchyEditor from './editors/ClassHierarchyEditor/meta'
import RadiosEditor from './editors/RadiosEditor/meta'
import DetailsEditor from './editors/DetailsEditor/meta'
import ShapeEditor from './editors/ShapeEditor/meta'
import BooleanSelectEditor from './editors/BooleanSelectEditor/meta'
import FileUploadEditor from './editors/FileUploadEditor/meta'
import AddressEditor from './editors/AddressEditor/meta'
import NumberFieldEditor from './editors/NumberFieldEditor/meta'
import EnumSelectEditor from './editors/EnumSelectEditor/meta'
import DatePickerEditor from './editors/DatePickerEditor/meta'
import DurationEditor from './editors/DurationEditor/meta'
import DetailsViewer from './viewers/DetailsViewer/meta'
import ColorViewer from './viewers/ColorViewer/meta'
import ImageViewer from './viewers/ImageViewer/meta'
import AddressViewer from './viewers/AddressViewer/meta'
import GeoViewer from './viewers/GeoViewer/meta'
import LabelViewer from './viewers/LabelViewer/meta'
import ValueTableViewer from './viewers/ValueTableViewer/meta'
import IconifyViewer from './viewers/IconifyViewer/meta'
import URIViewer from './viewers/URIViewer/meta'
import LiteralViewer from './viewers/LiteralViewer/meta'
import CountFacet from './facets/CountFacet/meta'
import TextFieldFacet from './facets/TextFieldFacet/meta'
import DateFacet from './facets/DateFacet/meta'
import CommaList from './lists/CommaList/meta'
import UnorderedList from './lists/UnorderedList/meta'
import NaturalLanguageList from './lists/NaturalLanguageList/meta'
import PropertyGroup from './groups/PropertyGroup/meta'
import HorizontalPropertyGroup from './groups/HorizontalPropertyGroup/meta'
import TabbedPropertyGroup from './groups/TabbedPropertyGroup/meta'
import CollapsiblePropertyGroup from './groups/CollapsiblePropertyGroup/meta'
import DrawerPropertyGroup from './groups/DrawerPropertyGroup/meta'

export const coreWidgets: {
  editors: WidgetItem[]
  viewers: WidgetItem[]
  facets: WidgetItem[]
  lists: WidgetItem<{ items: ReactNode[] }>[]
  groups: WidgetItem[]
} = {
  editors: [{ meta: TextFieldWithLangEditor, Component: lazy(() => import('./editors/TextFieldWithLangEditor/index')) },
{ meta: EditorJsEditor, Component: lazy(() => import('./editors/EditorJsEditor/index')) },
{ meta: TextFieldEditor, Component: lazy(() => import('./editors/TextFieldEditor/index')) },
{ meta: IconifyEditor, Component: lazy(() => import('./editors/IconifyEditor/index')) },
{ meta: AutoCompleteEditor, Component: lazy(() => import('./editors/AutoCompleteEditor/index')) },
{ meta: ColorEditor, Component: lazy(() => import('./editors/ColorEditor/index')) },
{ meta: URIEditor, Component: lazy(() => import('./editors/URIEditor/index')) },
{ meta: ClassHierarchyEditor, Component: lazy(() => import('./editors/ClassHierarchyEditor/index')) },
{ meta: RadiosEditor, Component: lazy(() => import('./editors/RadiosEditor/index')) },
{ meta: DetailsEditor, Component: lazy(() => import('./editors/DetailsEditor/index')) },
{ meta: ShapeEditor, Component: lazy(() => import('./editors/ShapeEditor/index')) },
{ meta: BooleanSelectEditor, Component: lazy(() => import('./editors/BooleanSelectEditor/index')) },
{ meta: FileUploadEditor, Component: lazy(() => import('./editors/FileUploadEditor/index')) },
{ meta: AddressEditor, Component: lazy(() => import('./editors/AddressEditor/index')) },
{ meta: NumberFieldEditor, Component: lazy(() => import('./editors/NumberFieldEditor/index')) },
{ meta: EnumSelectEditor, Component: lazy(() => import('./editors/EnumSelectEditor/index')) },
{ meta: DatePickerEditor, Component: lazy(() => import('./editors/DatePickerEditor/index')) },
{ meta: DurationEditor, Component: lazy(() => import('./editors/DurationEditor/index')) }],
  viewers: [{ meta: DetailsViewer, Component: lazy(() => import('./viewers/DetailsViewer/index')) },
{ meta: ColorViewer, Component: lazy(() => import('./viewers/ColorViewer/index')) },
{ meta: ImageViewer, Component: lazy(() => import('./viewers/ImageViewer/index')) },
{ meta: AddressViewer, Component: lazy(() => import('./viewers/AddressViewer/index')) },
{ meta: GeoViewer, Component: lazy(() => import('./viewers/GeoViewer/index')) },
{ meta: LabelViewer, Component: lazy(() => import('./viewers/LabelViewer/index')) },
{ meta: ValueTableViewer, Component: lazy(() => import('./viewers/ValueTableViewer/index')) },
{ meta: IconifyViewer, Component: lazy(() => import('./viewers/IconifyViewer/index')) },
{ meta: URIViewer, Component: lazy(() => import('./viewers/URIViewer/index')) },
{ meta: LiteralViewer, Component: lazy(() => import('./viewers/LiteralViewer/index')) }],
  facets: [{ meta: CountFacet, Component: lazy(() => import('./facets/CountFacet/index')) },
{ meta: TextFieldFacet, Component: lazy(() => import('./facets/TextFieldFacet/index')) },
{ meta: DateFacet, Component: lazy(() => import('./facets/DateFacet/index')) }],
  lists: [{ meta: CommaList, Component: lazy(() => import('./lists/CommaList/index')) },
{ meta: UnorderedList, Component: lazy(() => import('./lists/UnorderedList/index')) },
{ meta: NaturalLanguageList, Component: lazy(() => import('./lists/NaturalLanguageList/index')) }],
  groups: [{ meta: PropertyGroup, Component: lazy(() => import('./groups/PropertyGroup/index')) },
{ meta: HorizontalPropertyGroup, Component: lazy(() => import('./groups/HorizontalPropertyGroup/index')) },
{ meta: TabbedPropertyGroup, Component: lazy(() => import('./groups/TabbedPropertyGroup/index')) },
{ meta: CollapsiblePropertyGroup, Component: lazy(() => import('./groups/CollapsiblePropertyGroup/index')) },
{ meta: DrawerPropertyGroup, Component: lazy(() => import('./groups/DrawerPropertyGroup/index')) }],
}