name: Test SHACL manager

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    secrets: inherit
    with:
      package: '@shapething/shacl-manager'
      browser: true
