name: Test Typed SPARQL

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    secrets: inherit
    with:
      badge: test-typed-sparql
      package: '@shapething/typed-sparql'
