name: Test Text store

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    secrets: inherit
    with:
      badge: test-text-store
      package: '@shapething/textstore'
